// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//deleted previous code as it is a Prisma CLI-only package which is not installed by default.
//when TypeScript tries to compile this file it fails
//NestJS does not need this file at runtime
//Prisma works without it

export default {
  schema: "./prisma/schema.prisma",
};

